version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/MorganGeek/number2lcd"

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true